### ISSUE TITLE
Some escape sequences are not escaped from test output

### ISSUE THREAD

**Issue by XO39** [kwrooijen/cargo.el#103]
Just as in the pictures below.

Is there any way to remove them? they are really annoying when there are lot of tests.

<img width="586" alt="Screen Shot 2020-07-04 at 3 18 21 PM" src="https://user-images.githubusercontent.com/47403233/86508763-22767280-be15-11ea-83cb-3563f5c0c6be.png">
<img width="621" alt="Screen Shot 2020-07-04 at 3 17 33 PM" src="https://user-images.githubusercontent.com/47403233/86508756-18ed0a80-be15-11ea-8456-668f8f8a27f3.png">

**Comment by kwrooijen** [comment]
I don't seem to have this problem 
![image](https://user-images.githubusercontent.com/629436/86509238-bd0b8d00-bde6-11ea-9366-6f8fe688ded9.png)

Mind sharing some information about your Emacs configuration? Are you using Spacemacs / Doom Emacs / Prelude? Operating system / Emacs version?

**Comment by XO39** [comment]
@kwrooijen I'm using Emacs 27.0.91 (9.0) on Mac Catalina 10.15.5

Some time ago I used this function:
```elisp
(require 'ansi-color)
(defun endless/colorize-compilation ()
  "Colorize from `compilation-filter-start' to `point'."
  (let ((inhibit-read-only t))
    (ansi-color-apply-on-region
     compilation-filter-start (point))))

(add-hook 'compilation-filter-hook #'endless/colorize-compilation)
```
to remove escape sequences and display colors in the compilation buffer, without it there is no colors and escape sequence characters are all over the place. Not sure if there is a better way to do that though.

May I ask what packages/method you are using to correctly display colors in compilation mode (_carego-process mode in this case_)?

**Comment by kwrooijen** [comment]
This is my emacs configuration: https://github.com/kwrooijen/.emacs.d/

I don't have rust in my configuration at the moment. I simply added these two lines to test:

```emacs lisp
(use-package rust-mode :straight t)
(use-package cargo :straight t)
```

Other than that, I didn't add anything extra to get it to work. I'm running Pop_OS! 20.04, emacs 26.3

**Comment by XO39** [comment]
OK thanks, it might be something at my end that messes things up. I'll look more into it once I got time. Well close this for now.
