### ISSUE TITLE
Automatically scroll to end of the buffer in cargo process mode

### ISSUE THREAD

**Issue by DogLooksGood** [kwrooijen/cargo.el#123]
Hi, thanks for the great works on this project.

I want to know is it possible to scroll to the end of buffer after output printed in `cargo-process-mode` buffer.
When I run cargo check or test, I will focus on whether there is any error. So I want to see the bottom of the output.

**Comment by kwrooijen** [comment]
This isn't implemented yet, but I think it should be possible. We'd probably have to make the buffer accessible here https://github.com/kwrooijen/cargo.el/blob/794f902bb84437afcc5d677d4a7a996c1f98359b/cargo-process.el#L285

And then use something like:

```emacs lisp
(with-current-buffer process-buffer (end-of-buffer))
```

Not sure if this is correct though

**Comment by DogLooksGood** [comment]
It will be great if the feature could provided as an option.

**Comment by DogLooksGood** [comment]
I found if the cursor is at the end of the buffer, it will be scroll automatically to keep itself at the end during the output.

**Comment by roife** [comment]
Scrollings for buffers related to `compilation-mode` are controlled by the variable `compilation-scroll-output`, so there is no need for code modifications.
