### ISSUE TITLE
Remove `--Zunstable-options` from `cargo-process--command-clippy` and dependency on nightly

### ISSUE THREAD

**Issue by theJasonFan** [kwrooijen/cargo.el#125]
The referenced [issue ](https://github.com/rust-lang/rust-clippy/issues/4612) has been resolved since Rust 1.52. (Documented in https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#others-2).

Can we remove `--Zunstable-options` and the dependency  on an unstable release? 

I'm happy to open a PR.

**Comment by c02y** [comment]
`(setq  cargo-process--command-clippy "clippy")`
