### ISSUE TITLE
error in process filter: Wrong type argument: listp, compilation-mode

### ISSUE THREAD

**Issue by c02y** [kwrooijen/cargo.el#128]
Whenever I run a cargo command such as `cargo-process-run` or `cargo-process-build`, there will be a line
```
error in process filter: Wrong type argument: listp, compilation-mode
```
in minibuffer and `*Message*` buffer.

The commands work fine, but it keeps printing the error message ever time I run a cargo-process command.

I'm not sure this is a bug or not.

**Comment by kwrooijen** [comment]
I can't seem to reproduce this. Do you have any cargo specific configuration?

**Comment by c02y** [comment]
I'm using spacemacs, with extra configuration about cargo added.

Maybe I should post this issue in spacemacs repo.

**Comment by rinconjc** [comment]
Are you using Spacemacs? if so, this could be related to https://github.com/syl20bnr/spacemacs/issues/15198 . There's a PR for it

**Comment by c02y** [comment]
> Are you using Spacemacs? if so, this could be related to [syl20bnr/spacemacs#15198](https://github.com/syl20bnr/spacemacs/issues/15198) . There's a PR for it

Sorry for the delay, it seems the issue is fixed in Spacemacs. Thanks.
