### ISSUE TITLE
Active buffer moves around

### ISSUE THREAD

**Issue by blt** [kwrooijen/cargo.el#14]
Hi folks, 

I have a funny issue: the buffer being used doesn't seem to be re-used and 'jumps' around. Let's say I start like so and want to 'cargo run':

![screen shot 2016-05-17 at 12 59 51 pm](https://cloud.githubusercontent.com/assets/3579/15337173/416ab69c-1c2f-11e6-8061-abe152c1dbd1.png)

resulting in:

![screen shot 2016-05-17 at 1 00 14 pm](https://cloud.githubusercontent.com/assets/3579/15337182/4fed55bc-1c2f-11e6-9f7e-8e0b5ef1914d.png)

run again:

![screen shot 2016-05-17 at 1 00 55 pm](https://cloud.githubusercontent.com/assets/3579/15337197/681f78f4-1c2f-11e6-9e6f-6a1ec127ea5c.png)

run again:

![screen shot 2016-05-17 at 1 01 14 pm](https://cloud.githubusercontent.com/assets/3579/15337205/7543abe0-1c2f-11e6-8449-238f97302ba5.png)

etc:

![screen shot 2016-05-17 at 1 01 40 pm](https://cloud.githubusercontent.com/assets/3579/15337216/8415e1e2-1c2f-11e6-81d9-7c8b6a3ac00a.png)

Can't say I've ever seen this behaviour from other in-emacs builders. Is this expected?

**Comment by blt** [comment]
I'm poking around on this. I got a little progress by setting:

`'(special-display-regexps '("[ ]?[*][^*]+[*]"))`

in my customized variables but this interacts strangely. Now the existing cargo.el buffer seems to be destroyed and recreated without being allocated a new visible display.

**Comment by kwrooijen** [comment]
Hi @blt.
I can't seem to reproduce this issue on my Emacs setup, nor when using `emacs -q`. Can you check if it still happen on a clean setup for you?

There might be something with your specific Emacs configuration, maybe you made changes to `compilation`? That's what cargo.el is ultimately using.

**Comment by kwrooijen** [comment]
Just out of curiosity, try overriding cargo-process--cleanup with this (so just eval this):

``` elisp
(defun cargo-process--cleanup (buffer)
  "Clean up the old Cargo process BUFFER when a similar process is run."
  (when (get-buffer-process (get-buffer buffer))
    (delete-process buffer)))
```

**Comment by blt** [comment]
Hi @kwrooijen, 

I haven't gotten a chance to try on a clean emacs yet. I hope to do that soon. I can confirm that the eval'd snippet does resolve the jumping around. 

I haven't made explicit changes to `compilation` but I do have a fair number of packages installed that could very likely have fiddled with it. Will try to pin this down when I run on a clean emacs.

**Comment by kwrooijen** [comment]
I just changed the source to use the code snippet I posted. Seems to work fine for me. So once Melpa has the newest version you can remove it from your Emacs configuration.

**Comment by blt** [comment]
Thank you!
