### ISSUE TITLE
apply: Buffer name ‘*Cargo Test*’ is in use

### ISSUE THREAD

**Issue by gabrielelana** [kwrooijen/cargo.el#17]
When I use `cargo-process-test` only the first time the buffer is named "_Cargo Test_" the following times the buffer is "_Cargo Process_"

Same happens for other commands, only the first time the buffer has the correct name

I suppose that's because the first time a buffer named "_Cargo Process_" is created and then renamed "_Cargo Test_", the following time "_Cargo Process_" gets created and then the rename fails because there's another buffer with the same name

Out of curiosity, why do you do that? Why not just use `get-buffer-create`?

**Comment by kwrooijen** [comment]
Sorry for the late reply, missed your post. Seems that I introduced a bug by fixing another. I'll take a look at this

**Comment by kwrooijen** [comment]
Just made a patch, seems that `compilation-start` already uses `get-buffer-create` internally, so I should be able to just pass in the buffer name directly.
https://github.com/kwrooijen/cargo.el/commit/f9fb985afdc4768fcb754c89cab0aac382fc1225

Seems to be working for me, hopefully this won't be causing issue anymore.

**Comment by kwrooijen** [comment]
I'll close this ticket now, if it's still an issue please open a new one. Thanks for reporting!
