### ISSUE TITLE
How can I build / run / test in release mode?

### ISSUE THREAD

**Issue by shepmaster** [kwrooijen/cargo.el#26]
Thanks for the useful library! Sometimes, I have code that really needs the optimizations from `--release` to be efficient. How can I pass that flag along? 

I didn't see anything obvious in the README or in a quick perusal of the source.

**Comment by kwrooijen** [comment]
If you add the negative argument `C--` you can modify the command.

For example:
`C-- C-c C-c C-t`
Will prompt you to modify the cargo test command

After you've written the command you can run `C-c C-c C-c` to repeat it with the extra arguments you've added.

Not sure if this is what you meant, but hope it helps!

**Comment by shepmaster** [comment]
Yes, it is what I meant. In my case, <kbd>C--</kbd> is bound to `undo` (which I believe to be a default?), so the full sequence is

<kbd>C-u</kbd> <kbd>-</kbd> <kbd>C-c</kbd> <kbd>C-c</kbd> <kbd>C-t</kbd> <kbd> --release</kbd> <kbd>Enter</kbd>

Although *just* using the prefix argument (<kbd>C-u</kbd>) works, so

<kbd>C-u</kbd> <kbd>C-c</kbd> <kbd>C-c</kbd> <kbd>C-t</kbd> <kbd> --release</kbd> <kbd>Enter</kbd>

**Comment by kwrooijen** [comment]
Emacs by default has `C--` set to negative argument, and `C-_` to undo. (From looking at `emacs -q`)

Seems like your issue is resolved, if you have any other troubles just open a new ticket.

**Comment by shepmaster** [comment]
> Emacs by default has C-- set to negative argument, and C-_ to undo

Ah, you are right, this must be an macOS / terminal emulation issue, as <kbd>C--</kbd> *reports* as <kbd>C-_</kbd> for me. *shrug*
