### ISSUE TITLE
Cargo-process is not font-locked immediately

### ISSUE THREAD

**Issue by sooheon** [kwrooijen/cargo.el#27]
For example, upon running cargo-process-run, I get the results in the buffer fine, but it takes some kind of input (movement or other command) to font lock. Is this a known issue?

**Comment by kwrooijen** [comment]
Not that I'm aware of, could you test this with a minimal emacs config? Here's a snippet

```` lisp
(require 'package)
(require 'ert)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(use-package cargo
  :ensure t
  :init
  (add-hook 'rust-mode-hook 'cargo-minor-mode))
````

**Comment by sooheon** [comment]
Hm, emacs -Q with your snippet does not have the issue, so looks like config bug hunting for me :) I'll update result here. Thanks

**Comment by sooheon** [comment]
Ok, I've figured out that this is due to my setting `(setq jit-lock-defer-time 0)` which defers font-locking while user input is pending. I think cargo should gracefully deal with this, because the expected behavior is to always font-lock eagerly unless I am actively inputting commands.

**Comment by kwrooijen** [comment]
I'm not really familiar with this variable or how to solve this issue because of it. Do you have any idea? Would we need to use something like redraw-display?

**Comment by sooheon** [comment]
Not sure. Actually, I've tested some more with just compile.el buffers, and they have the same problem. So this is not an issue for cargo.el

**Comment by kwrooijen** [comment]
Since this is not really a cargo.el specific issue, I'm closing this for now.
