### ISSUE TITLE
cargo runs from the wrong directory

### ISSUE THREAD

**Issue by dsvensson** [kwrooijen/cargo.el#31]
`(cargo-process--project-root)` returns the directory of `Cargo.toml`, but cargo is not run from that directory, which messes up `cargo clippy` for example:

    src> cargo clippy
    thread 'main' panicked at 'could not find matching package', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:715
    note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by wjlroe** [comment]
Until this mode gets updated/changed in any way, you can get the bahaviour you need using the following elisp in your config:

```elisp
  (defun my-set-default-dir-cargo-run (orig-fun &rest args)
    (let* ((project-root (cargo-process--project-root))
           (default-directory (if project-root
                                  project-root
                                default-directory)))
      (apply orig-fun args)))

  (advice-add 'cargo-process--start :around #'my-set-default-dir-cargo-run)
```

That snippet will run any cargo command in a scope that includes `default-directory` set to the project root (if that can be resolved).

**Comment by kwrooijen** [comment]
I've applied the change here: https://github.com/kwrooijen/cargo.el/commit/156574632e47e49aeb7d17c1d2344e10c06c3acb

I've tested it and it seems to be running the command from the root directory now. If you're having any more issues please open a new ticket.
