### ISSUE TITLE
Key binding for cargo-process-doc-open overrides help binding

### ISSUE THREAD

**Issue by jturner314** [kwrooijen/cargo.el#36]
The binding `C-c C-c C-h` was recently added (4fdf141e33044c81f1ba776f0146fe25797561e4) for `cargo-process-doc-open`. Unfortunately, this prevents use of `C-c C-c C-h` to access help for the `C-c C-c` prefix. See the [Emacs Key Binding Conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html):

> Don’t bind `C-h` following any prefix character (including `C-c`). If you don’t bind `C-h`, it is automatically available as a help character for listing the subcommands of the prefix character.

I suggest switching to a different key binding for `cargo-process-doc-open`. A good option is `C-c C-c C-v`, which reminds me of "view".

By the way, thanks for creating this minor mode! I use it constantly, and it really speeds up working with Rust.

**Comment by kwrooijen** [comment]
Hi @jturner314 
Thanks for reporting this, I've changed it to `C-v` in the latest commit. Was a bit of a silly mistake on my part. Glad this mode is useful to you though!

If you run into more problems, feel free to open a new issue.
