### ISSUE TITLE
Set RUST_BACKTRACE environment variable prior to running

### ISSUE THREAD

**Issue by TyOverby** [kwrooijen/cargo.el#37]
The RUST_BACKTRACE env-var should basically always be set while developing.

**Comment by kwrooijen** [comment]
Sorry for the really late response. I'm not really sure what this var is supposed to do (haven't done Rust dev in a while). Normally I'd say the system should change env vars, not elisp packages. But if this is a really good feature to have within emacs then I wouldn't mind creating a var, nil by default, which would enable this.

**Comment by TyOverby** [comment]
Rust programs don't print stacktraces on panic by default.  

`RUST_BACKTRACE=1 cargo test` is the recommended way to run tests.

**Comment by kwrooijen** [comment]
Does that mean this would only be used for tests, or is it just an example usage?

**Comment by TyOverby** [comment]
`cargo test` and `cargo run`

**Comment by kwrooijen** [comment]
Just added this to master. It should be synced with Melpa soon.
To enable: `(setq cargo-process--enable-rust-backtrace t)`

Again, sorry for the delay

**Comment by kwrooijen** [comment]
Closing the ticket now. If this isn't resolved or you come across other problems, please open a new issue. Thanks!
