### ISSUE TITLE
Easily fixable bug - cargo-processs-run-bin doesnt take an interactive argument

### ISSUE THREAD

**Issue by jsalzbergedu** [kwrooijen/cargo.el#38]
As the title says. You would expect it to let you feed it the name of the bin you are trying to run, but it doesnt. In cargo-process.el, if you change `(interactive)` to `(interactive "sName (leave empty for none): ")`, it behaves as I would expect it to.

Thanks, and thanks for this free peice of software that makes things more convenient!

**Comment by kwrooijen** [comment]
Thanks for reporting, should be fixed in https://github.com/kwrooijen/cargo.el/commit/b0487f95a7de7a1d6f03cdd05220f633977d65a2

If this didn't fix the issue please let me know
