### ISSUE TITLE
cargo-process-current-test not run current test

### ISSUE THREAD

**Issue by Dushistov** [kwrooijen/cargo.el#39]
I use `tests` template that provide `cargo new`:
```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {}
}
```

if I put cursor to `it_wors` and command emacs: `M-x cargo-process-current-test`
it run `cargo test lib::it_works`, and `running 0 tests` as result.

It should run `cargo test tests::it_works` to really run `it_works`.

**Comment by kwrooijen** [comment]
Hi, thank you for reporting. I just pushed a fix for this. Let me know if the issue still persists.

While I was resolving this issue I found out that `cargo-process-current-file-tests` was also broken. I somewhat fixed it by looking up the module the tests are nested in, and run those tests. But when there are multiple modules in a file it won't run all of them. I couldn't find any way to run tests in a specific file with plain Cargo though, any idea?

**Comment by Dushistov** [comment]
@kwrooijen Thanks for fix, I will try it as long as it appears at melpa.

> I couldn't find any way to run tests in a specific file with plain Cargo though, any idea?

You can run `cargo check --tests`, parse `.rmeta` file (may be with https://github.com/nrc/rls-analysis help) and know all about code structure in whole crate,

but I suppose it is too much work.

May be better integrate with [lsp-rust](https://github.com/emacs-lsp/lsp-rust) and
get suitable info about code structure from [rls](https://github.com/rust-lang-nursery/rls)?

Then integrate with something like [this](https://www.gnu.org/software/emacs/manual/html_node/ede/Creating-a-project.html) and make possible to run/test/debug project with nice menu and other stuff expecting from IDE

**Comment by Dushistov** [comment]
Thanks again, I tested, all works.

**Comment by Dushistov** [comment]
Reopen with such test case:

```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_foreign_types_names_map_parsing() {
        let parse_sess = ParseSess::new();
        let types_map = parse_types_map(
            &parse_sess,
            "test",
            r#"
mod foreign_types_map {
    #![foreigner_type="boolean"]
    #![rust_type="jboolean"]
    #![foreigner_type="short"]
    #![rust_type="jshort"]
    #![foreigner_type="int"]
    #![rust_type="jint"]
}
"#,
        );
        assert_eq!(vec![(Symbol::intern("boolean"), Symbol::intern("jboolean")),
                        (Symbol::intern("int"), Symbol::intern("jint")),
                        (Symbol::intern("short"), Symbol::intern("jshort"))],
                   {
                       let mut ret = vec![];
                       for (fsym, idx) in &types_map.foreign_names_map {
                           let rust_sym = types_map.conv_graph[*idx].frontier_ref_unwrap().rust;
                           ret.push((*fsym, rust_sym));
                       }
                       ret.sort_by(|a, b| a.0.as_str().cmp(&b.0.as_str()));
                       ret
                   });
    }

    #[test]
    fn test_foreign_type_map_parsing() {
        let parse_sess = ParseSess::new();
        let types_map = parse_types_map(
            &parse_sess,
            "test",
            r#"
mod foreign_types_map {
    #![foreigner_type="boolean"]
    #![rust_type="jboolean"]
    #![foreigner_type="int"]
    #![rust_type="jint"]
}

impl SwigInto<bool> for jboolean {
    fn swig_into(self, _: *mut JNIEnv) -> bool {
        self != 0
    }
}

impl SwigFrom<bool> for jboolean {
    fn swig_from(x: bool, _: *mut JNIEnv) -> Self {
        if x { 1 as jboolean } else { 0 as jboolean }
    }
}

impl SwigFrom<i32> for jint {
    fn swig_from(x: i32, _: *mut JNIEnv) -> Self {
        x
    }
}
"#,
        );
        assert_eq!(types_map
                       .to_foreign_type_name(Symbol::intern("bool"))
                       .unwrap()
                       .0,
                   Symbol::intern("boolean"));

        assert_eq!(types_map
                       .to_foreign_type_name(Symbol::intern("i32"))
                       .unwrap()
                       .0,
                   Symbol::intern("int"));
    }
}
```

As you mention in https://github.com/kwrooijen/cargo.el/issues/41#issuecomment-319317831 there was issue in rust-lang/rust-mode , but at now rust-lang/rust-mode#222 was fixed 

and if I put cursor to the last - 1 `assert_eq!` `M-x rust-beginning-of-defun` jump to `test_foreign_type_map_parsing`, so at now rust-mode works correctly,

any ideas why `M-x cargo-process-current-test` gives `Unable to find test`?

**Comment by kwrooijen** [comment]
Pushed a fix, let me know if this resolves the issue

**Comment by Dushistov** [comment]
@kwrooijen 
> Pushed a fix, let me know if this resolves the issue

Works for me, thanks.
