### ISSUE TITLE
highlight errors with explain identifiers, `error[E123]`

### ISSUE THREAD

**Issue by blaenk** [kwrooijen/cargo.el#40]
Currently errors without explain identifiers are highlighted. Those errors _with_ explain identifiers aren't highlighted (i.e. the word "error" isn't highlighted so as to stand out), although the identifier itself does have a face.

Would it be possible to highlight the word "error" for those cases which include an explain identifier? I style them red so that they stand out to me when skimming the log, and it looks weird that these aren't.

One way to accomplish this might be to use negative lookaheads, which elisp doesn't have. The simpler way might be to simply match on any error at the beginning of a line, which I think should be safe. I don't think the word "error" would appear at the beginning of a line unless it were an error. Here's the result on my end:

![error styling](https://i.imgur.com/PYWzUNq.png)

I did this by simply changing the pattern to:

``` elisp
"^error\\:?"
```

I'm not sure if warnings also ever contain explain identifiers, if so it may be useful to do the same with its pattern.

**Comment by kwrooijen** [comment]
Hey, thanks for reporting this.

I think adjusting the regexp like this is fine. I probably didn't check if "error" was at the beginning of the line because the format was different back then (for what I can remember).

This seems like a safe change though, I'll apply it to both error and warning.

**Comment by kwrooijen** [comment]
Just pushed it to master, should sync with Melpa soon. https://github.com/kwrooijen/cargo.el/commit/f318b5ce6b371355ab4adc0f1a6c5ab2409e91e9

If there are any more issues please open a new issue. Thanks!

**Comment by blaenk** [comment]
Much appreciated!
