### ISSUE TITLE
feature request: rustfmt-nightly support

### ISSUE THREAD

**Issue by Dushistov** [kwrooijen/cargo.el#42]
According to [this](https://users.rust-lang.org/t/rustfmt-releases/11357) `rustfmt` package in future will be obsolete. And current mainstream is `rustfmt-nightly` crate, which in future become part of standrard rust dictirbituion.

But at now it is impossible to use `rustfmt-nightly` if you want to use stable `rustc/cargo` at the same time. To run rustfmt nightly and use as default stable branch of `rustc/cargo` you need such commands: `cargo +nightly fmt` or `rustup run nightly cargo fmt`.

I can not see how to configure `cargo.el` to use one of theese commands in `M-x cargo-process-fmt`. As work around I can only create custom shell script `cargo`, set path to it via `cargo-process--custom-path-to-bin`, and in this script forward comamnds to suitable versions of cargo, not neat.

May be possible to create configuration like `cargo-process--custom-cargo-fmt-command`?

**Comment by kwrooijen** [comment]
Hey,

I like the idea of being able to adjust the command string through config. I can implement this for all commands, wouldn't be much work.

**Comment by kwrooijen** [comment]
Added the change, you can change the command by adding the following line to your emacs config:

```el
(setq cargo-process--command-fmt "cargo +nightly fmt")
```

**Comment by Dushistov** [comment]
Thanks, at now it works for me.
