### ISSUE TITLE
C-S-k cannot be typed on a terminal

### ISSUE THREAD

**Issue by uazu** [kwrooijen/cargo.el#57]
Terminal users need another way to conveniently access clippy. Thanks

**Comment by kwrooijen** [comment]
I don't think I'd want to change the current keybindings. But you can always add custom bindings to your Emacs config, e.g.


``` Emacs Lisp
(define-key cargo-minor-mode-map (kbd "C-c C-c C-p") 'cargo-process-clippy)
```

**Comment by uazu** [comment]
Thanks for the workaround. Ideally this workaround needs documenting so that terminal users know what to do.
