### ISSUE TITLE
Error when using new or init

### ISSUE THREAD

**Issue by admintome** [kwrooijen/cargo.el#59]
When I try to create a cargo package with new or init it asks me for the project name then asks if i want to create a bin project to which i answer yes.  I then get a Json readtable error: 101

it doesn't matter if i enter y or no for the bin project the error is the same.  Did I configure something incorrectly?

Here is the config file i am using:
https://github.com/admintome/emacs-rust/blob/master/emacs-el

**Comment by kwrooijen** [comment]
Seems to be an issue on our end, I'll have a look at it tomorrow

**Comment by anquegi** [comment]
Same issue here, when using new, I get the same error:
`
json-read: JSON readtable error: 101`

the problem seems that need a toml file

```
Debugger entered--Lisp error: (json-readtable-error 101)
  signal(json-readtable-error (101))
  json-read()
  json-read-from-string("error: could not find `Cargo.toml` in `/Users/toni/learn/rust` or any parent directory\n")
  cargo-process--workspace-root()
  cargo-process--start("New" "new patata --bin")
  cargo-process-new("patata")
  funcall-interactively(cargo-process-new "patata")
  call-interactively(cargo-process-new record nil)
  command-execute(cargo-process-new record)
  execute-extended-command(nil "cargo-process-new" "cargo-process-ne")
  funcall-interactively(execute-extended-command nil "cargo-process-new" "cargo-process-ne")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by kwrooijen** [comment]
Hi, sorry it took so long, busy as always.

This commit _should_ fix the issue https://github.com/kwrooijen/cargo.el/commit/93ab6c436c77e090e11bb0434c09abdadc2a2e99

I should really look into writing some tests for Elisp packages. Let me know if the issue persists / new issues arise. Thanks!
