### ISSUE TITLE
Pass params to the cargo test

### ISSUE THREAD

**Issue by TatriX** [kwrooijen/cargo.el#60]
Hi. I want to run my tests as:
```
cargo test -- --test-threads=1   --nocapture 
```
Is it possible now?

**Comment by kwrooijen** [comment]
Hi!

You can modify the arguments by using the `negative-argument` command (`C--`).

`C-- C-c C-c C-t` and fill in your extra arguments (you can afterwards press `C-c C-c C-c` to repeat)

**Comment by TatriX** [comment]
Cool, thank you!
