### ISSUE TITLE
feature request: provide a way to pass (default) features to build

### ISSUE THREAD

**Issue by igalic** [kwrooijen/cargo.el#73]
I'm working on a rust project that doesn't really [`build` by default](https://github.com/Plume-org/Plume/blob/master/docs/INSTALL.md#running-migrations)

Is there a way to override the `defvar`s such as `cargo-process--command-build`?
If that's not possible, we could introduce overridable default options for the cargo command-line?

**Comment by mookid** [comment]
Did you try to use the prefix argument, as documented in the docstring?

C-u C-c C-c C-b should prompt you for the command to run.

**Comment by r-darwish** [comment]
@mookid it works, but I have to do it every time. It always like to run `cargo check --all-features` for all of my projects. Customizing `cargo-process--command-flags` breaks commands such as `cargo add`, so an additional variables that passes arguments only to build functions `check, build, doc, test` will be awesome.

**Comment by mookid** [comment]
Ok, I understand.

+ Does (setq cargo-process--command-check "check --all") in your case?

+ Note that even if it is not a persistent customization, you can use cargo-process-repeat for that purpose.


edit: it is actually documented in README.md: 
```
Commands can be adjusted by changing their command variable.
Here's a list of commands and their default value.

```
