### ISSUE TITLE
Can't build or run tests

### ISSUE THREAD

**Issue by bbigras** [kwrooijen/cargo.el#84]
I get: `json-read: JSON readtable error: 47`

GNU Emacs 26.1
rustc 1.36.0-nightly (7c71bc320 2019-04-30)

I use direnv (with direnv-mode). cargo and rustc are not available on my system without it.

**Comment by kwrooijen** [comment]
With https://github.com/kwrooijen/cargo.el/pull/99 merged, the error messages should be clear. Closing this. Open if this isn't the case.

**Comment by bbigras** [comment]
Thanks.
