### ISSUE TITLE
Any cargo-process-* command gives JSON error

### ISSUE THREAD

**Issue by johalun** [kwrooijen/cargo.el#86]
The error is
JSON readtable error: 79

All packages up to date.
Emacs 26.2
FreeBSD 13

**Comment by gatoWololo** [comment]
This happens to me when the `cargo` command failed for some reason. I would try manually doing the command you're attempting in the terminal, and see if it works there first.

**Comment by kwrooijen** [comment]
With https://github.com/kwrooijen/cargo.el/pull/99 merged, the error messages should be clear. Closing this. Open if this isn't the case.
