### ISSUE TITLE
Run Example

### ISSUE THREAD

**Issue by MasonRemaley** [kwrooijen/cargo.el#9]
Is it currently possible to set up a shortcut to run `cargo run --example <name>`? (I'm new to emacs--apologies if there's an obvious place to set this up that I'm just not seeing.)

**Comment by smaximov** [comment]
@MasonRemaley, one option is to hit <kbd>C-u C-c C-c C-r</kbd> (i.e., invoke the keybinding for `cargo-process-run` with the prefix argument), then edit  the command in the minibuffer (append " --example <name>") and hit <kbd>RET</kbd>.

Another option requires a little Elisp knowledge. Put the following snippet in your init file:

``` lisp
(defun cargo-process-example (command)
  (interactive
   (list (cargo-process--maybe-read-command
          (concat "cargo run --example "
                  (read-string "Example name: ")))))
  (cargo-process-run command))

(define-key cargo-minor-mode-map (kbd "C-c C-c C-x") #'cargo-process-example)
;; Or if you want a global shortcut:
;; (global-set-key (kbd "C-c C-c C-x") #'cargo-process-example)
```

The snippet defines an interactive command `cargo-process-example` and set the shortcut <kbd>C-c C-c C-x</kbd> to run this command. When invoked, `cargo-process-example` first prompts for the name of the example, then runs the example.

Maybe it's worth adding this command to `cargo.el`.

**Comment by MasonRemaley** [comment]
That works, thanks! Having that snippet in `cargo.el` by default could be nice (though at the same time, I don't know that other people run examples as often as I do.)

**Comment by kwrooijen** [comment]
I think it would be fine to have this command. I'll add it.
